echo "very common commands, and what they do"
echo "sudo - tool predominantly used for gaining root privileges for a certain command. sudo -s is useful for getting root for the rest of the session."
echo "cd /path/to/dir - changes dir path. if you wanna go to home dir, just type cd."
echo "cp /path/to/file /new/file/location/ - copies file from one place, to another."
echo "ls - lists all files and sub-directories in the dir you are in."
echo "git clone - copies repo to your computer. requires access to outside world (the internet)"
echo "rm - a very useful command, for removing files. rm -rf forces a file/non-empty dir to be deleted. Dangerous if misused."
echo "shutdown - shuts down the computer. self explanatory."
echo "reboot - again, it does what it says."